import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coming Soon...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <div className="m-auto">
          <h1 className="text-blue-400 text-4xl font-bold">BackslashFlutter</h1>
          <h3 className="text-white text-center animate-bounce p-10">Coming Soon...</h3>
          
        </div>
      </div>
      
      
 
      
    </div>
  )
}
